### PR TITLE
refactor: rename dirs

### PR DESCRIPTION
**Pull request by andreivladbrg**
Closes https://github.com/sablier-labs/v2-deployments/issues/8

### CODE REVIEW

**Review by smol-ninja — APPROVED** [review]
LGTM.

**Comment by smol-ninja** [comment]
What about point 1 in the linked issue: `Rename zk_sync to zk-sync`?

**Comment by andreivladbrg** [comment]
> What about point 1 in the linked issue: `Rename zk_sync to zk-sync`?

what do you mean?

image

**Comment by smol-ninja** [comment]
nvm. I overlooked it. Feel free to merge it.

**Pull request merged**
